language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
env: NODE_ENV=development
before_install:
  - sudo add-apt-repository -y ppa:dhor/myway
  - sudo apt-get install -y imagemagick graphicsmagick
branches:
  only:
    - master
