language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
env: NODE_ENV=development
before_install:
  - sudo apt-get install imagemagick
  - sudo apt-get install graphicsmagick
branches:
  only:
    - master
