language: node_js
node_js:
  - "8.0.0"
  - "10.16.0"
env: NODE_ENV=development
before_install:
  - sudo add-apt-repository -y ppa:dhor/myway
  - sudo apt-get update
  - sudo apt-get install -y imagemagick 
  - sudo apt-get install -y graphicsmagick
